---
galaxy_info:
  author: SoloText Team
  description: Rôle pour la configuration du reverse proxy Nginx et SSL
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - nginx
    - ssl
    - proxy

dependencies: []

