---
galaxy_info:
  author: SoloText Team
  description: Rôle pour le build et déploiement du frontend Vue.js
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - frontend
    - vuejs
    - nginx

dependencies: []

