---
# Playbook pour le déploiement sur l'environnement de staging

- name: Déploiement SoloText sur Staging
  hosts: staging
  become: yes
  gather_facts: yes

  vars:
    deployment_env: staging

  vars_files:
    - "{{ inventory_dir }}/group_vars/staging.yml"
    - "{{ inventory_dir }}/group_vars/staging/vault.yml"

  roles:
    - role: common
    - role: app
    - role: nginx_proxy

