---
galaxy_info:
  author: SoloText Team
  description: Rôle pour la configuration PostgreSQL avec Docker
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - database
    - postgresql
    - docker

dependencies: []

